//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int CustomerID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
    }
}
