//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int InvoiceNo { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<int> Total_Units { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
    }
}
