//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int ProductID { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public decimal Purchase_Price { get; set; }
        public decimal Selling_price { get; set; }
        public int Quantity { get; set; }
    }
}
